### ISSUE TITLE
Write meta-documentation

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#18]
I am referring to the expansion of README in separated pages, to be integrated to Sphinx build in the `gh-pages` branch.  I am currently thinking of:
- [x] Overview (`index.rst`)
- [x] Installation
- [ ] Sample usage and/or guides
- [x] Reference
- [x] Design principles
- [x] Contribution guidelines (also CONTRIBUTING.md in `master`)
- [x] License and Credits

Feel free to add pages you believe to be necessary to the list.  I'm not going to enforce much on the `gh-pages` branch so you can push changes directly there.

**Comment by Huy-Ngo** [comment]
Some questions on my mind:

- How do we add those things other than reference into the pages? I don't think I should push write them in html and put it in `html/`. I've never used Sphinx or any documentation tool before, so I don't know how to use it. 
- Overview: Can we reuse the proposal or write based on it?
- Contribution guidelines: Would it look something like [this](https://flask.palletsprojects.com/en/1.1.x/styleguide/) and/or [this](https://flask.palletsprojects.com/en/1.1.x/contributing/)
- License & Credits: Just restating `LICENSE` and give credits to alure?

**Comment by McSinyx** [comment]
> How do we add those things other than reference into the pages?

Just add the restructure text to the `src` directory.  Read `index.rst` to see how they're linked together.  I'm not experienced with RST enough to instruct any further.

> Overview: Can we reuse the proposal or write based on it?

I don't know TBH.  What I do know is that it should be in the **users'** perspective.

> Contribution guidelines: Would it look something like [...]

Yes, and adapted to our case.  It should at least cover
* How to file a bug report/feature request and what info should be provided?
* How and when (i.e. after discussion) to send us a patch and what to check before submitting it?

See one I wrote some time ago [here](https://github.com/vicious-widgets/vicious/blob/master/CONTRIBUTING.md).  Note that the situation there is very different due to the nature of the projects (the other is supposed to be resistant to more often upstream changes, and to be modular, i.e. expecting new stuff to be added).

> License & Credits: Just restating LICENSE and give credits to alure?

We are legally required to state the licenses of statically linked libraries whose licenses require it (which mean all of them IIRC).  Credits are for stuff that deserved to be honored but does not get distributed, e.g. Sphinx, your text editor, the CI tools, your primary school teachers (I really hope they are not distributed), etc.

**Comment by McSinyx** [comment]
Closing in favor or GH-93.
